name: continuous-delivery
on:
  push:
    branches: [main]
jobs:
  semver-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ohpensource/platform-cicd/actions/git/generate-version-and-release-notes@2.15.0.1
        name: semver & changelog
        with:
          user-email: "github-svc@ohpen.com"
          user-name: "GitHub Actions"
      - id: semver
        run: echo "::set-output name=service-version::$(cat ./version.json | jq -r '.version')"
